"""Database models"""
from sqlalchemy import Column, Integer, String, Numeric, Boolean, ForeignKey
from app.database import Base


class AdvancedSkaterStats(Base):
    """Advanced skater statistics model matching advanced_skater_stats table schema"""
    __tablename__ = "advanced_skater_stats"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(Integer, ForeignKey("player_info.id", ondelete="CASCADE"), nullable=False)
    contract_id = Column(Integer, ForeignKey("contracts.id", ondelete="CASCADE"), nullable=False)
    season = Column(Integer, nullable=False)
    playoff = Column(Boolean, nullable=False, default=False)
    team = Column(String(50), nullable=False)
    situation = Column(String(20), nullable=False)
    
    games_played = Column(Integer, nullable=True)
    icetime = Column(Numeric(10, 2), nullable=True)
    shifts = Column(Integer, nullable=True)
    game_score = Column(Numeric(6, 2), nullable=True)
    
    on_ice_x_goals_percentage = Column(Numeric(5, 4), nullable=True)
    off_ice_x_goals_percentage = Column(Numeric(5, 4), nullable=True)
    on_ice_corsi_percentage = Column(Numeric(5, 4), nullable=True)
    off_ice_corsi_percentage = Column(Numeric(5, 4), nullable=True)
    on_ice_fenwick_percentage = Column(Numeric(5, 4), nullable=True)
    off_ice_fenwick_percentage = Column(Numeric(5, 4), nullable=True)
    ice_time_rank = Column(Integer, nullable=True)
    
    i_f_x_on_goal = Column(Numeric(8, 2), nullable=True)
    i_f_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_x_rebounds = Column(Numeric(8, 2), nullable=True)
    i_f_x_freeze = Column(Numeric(8, 2), nullable=True)
    i_f_x_play_stopped = Column(Numeric(8, 2), nullable=True)
    i_f_x_play_continued_in_zone = Column(Numeric(8, 2), nullable=True)
    i_f_x_play_continued_outside_zone = Column(Numeric(8, 2), nullable=True)
    i_f_flurry_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_score_venue_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_flurry_score_venue_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_primary_assists = Column(Integer, nullable=True)
    i_f_secondary_assists = Column(Integer, nullable=True)
    i_f_shots_on_goal = Column(Integer, nullable=True)
    i_f_missed_shots = Column(Integer, nullable=True)
    i_f_blocked_shot_attempts = Column(Integer, nullable=True)
    i_f_shot_attempts = Column(Integer, nullable=True)
    i_f_points = Column(Integer, nullable=True)
    i_f_goals = Column(Integer, nullable=True)
    i_f_rebounds = Column(Integer, nullable=True)
    i_f_rebound_goals = Column(Integer, nullable=True)
    i_f_freeze = Column(Integer, nullable=True)
    i_f_play_stopped = Column(Integer, nullable=True)
    i_f_play_continued_in_zone = Column(Integer, nullable=True)
    i_f_play_continued_outside_zone = Column(Integer, nullable=True)
    i_f_saved_shots_on_goal = Column(Integer, nullable=True)
    i_f_saved_unblocked_shot_attempts = Column(Integer, nullable=True)
    i_f_penalties = Column(Integer, nullable=True)
    i_f_penalty_minutes = Column(Integer, nullable=True)
    i_f_faceoffs_won = Column(Integer, nullable=True)
    i_f_hits = Column(Integer, nullable=True)
    i_f_takeaways = Column(Integer, nullable=True)
    i_f_giveaways = Column(Integer, nullable=True)
    i_f_low_danger_shots = Column(Integer, nullable=True)
    i_f_medium_danger_shots = Column(Integer, nullable=True)
    i_f_high_danger_shots = Column(Integer, nullable=True)
    i_f_low_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_medium_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_high_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_low_danger_goals = Column(Integer, nullable=True)
    i_f_medium_danger_goals = Column(Integer, nullable=True)
    i_f_high_danger_goals = Column(Integer, nullable=True)
    i_f_score_adjusted_shot_attempts = Column(Integer, nullable=True)
    i_f_unblocked_shot_attempts = Column(Integer, nullable=True)
    i_f_score_adjusted_unblocked_shot_attempts = Column(Integer, nullable=True)
    i_f_d_zone_giveaways = Column(Integer, nullable=True)
    i_f_x_goals_from_x_rebounds_of_shots = Column(Numeric(8, 2), nullable=True)
    i_f_x_goals_from_actual_rebounds_of_shots = Column(Numeric(8, 2), nullable=True)
    i_f_rebound_x_goals = Column(Numeric(8, 2), nullable=True)
    i_f_x_goals_with_earned_rebounds = Column(Numeric(8, 2), nullable=True)
    i_f_x_goals_with_earned_rebounds_score_adjusted = Column(Numeric(8, 2), nullable=True)
    i_f_x_goals_with_earned_rebounds_score_flurry_adjusted = Column(Numeric(8, 2), nullable=True)
    i_f_shifts = Column(Integer, nullable=True)
    i_f_o_zone_shift_starts = Column(Integer, nullable=True)
    i_f_d_zone_shift_starts = Column(Integer, nullable=True)
    i_f_neutral_zone_shift_starts = Column(Integer, nullable=True)
    i_f_fly_shift_starts = Column(Integer, nullable=True)
    i_f_o_zone_shift_ends = Column(Integer, nullable=True)
    i_f_d_zone_shift_ends = Column(Integer, nullable=True)
    i_f_neutral_zone_shift_ends = Column(Integer, nullable=True)
    i_f_fly_shift_ends = Column(Integer, nullable=True)
    
    faceoffs_won = Column(Integer, nullable=True)
    faceoffs_lost = Column(Integer, nullable=True)
    time_on_bench = Column(Integer, nullable=True)
    penalty_minutes = Column(Integer, nullable=True)
    penalty_minutes_drawn = Column(Integer, nullable=True)
    penalties_drawn = Column(Integer, nullable=True)
    shots_blocked_by_player = Column(Integer, nullable=True)
    
    on_ice_f_x_on_goal = Column(Numeric(8, 2), nullable=True)
    on_ice_f_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_flurry_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_score_venue_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_flurry_score_venue_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_shots_on_goal = Column(Integer, nullable=True)
    on_ice_f_missed_shots = Column(Integer, nullable=True)
    on_ice_f_blocked_shot_attempts = Column(Integer, nullable=True)
    on_ice_f_shot_attempts = Column(Integer, nullable=True)
    on_ice_f_goals = Column(Integer, nullable=True)
    on_ice_f_rebounds = Column(Integer, nullable=True)
    on_ice_f_rebound_goals = Column(Integer, nullable=True)
    on_ice_f_low_danger_shots = Column(Integer, nullable=True)
    on_ice_f_medium_danger_shots = Column(Integer, nullable=True)
    on_ice_f_high_danger_shots = Column(Integer, nullable=True)
    on_ice_f_low_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_medium_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_high_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_low_danger_goals = Column(Integer, nullable=True)
    on_ice_f_medium_danger_goals = Column(Integer, nullable=True)
    on_ice_f_high_danger_goals = Column(Integer, nullable=True)
    on_ice_f_score_adjusted_shot_attempts = Column(Integer, nullable=True)
    on_ice_f_unblocked_shot_attempts = Column(Integer, nullable=True)
    on_ice_f_score_adjusted_unblocked_shot_attempts = Column(Integer, nullable=True)
    on_ice_f_x_goals_from_x_rebounds_of_shots = Column(Numeric(8, 2), nullable=True)
    on_ice_f_x_goals_from_actual_rebounds_of_shots = Column(Numeric(8, 2), nullable=True)
    on_ice_f_rebound_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_f_x_goals_with_earned_rebounds = Column(Numeric(8, 2), nullable=True)
    on_ice_f_x_goals_with_earned_rebounds_score_adjusted = Column(Numeric(8, 2), nullable=True)
    on_ice_f_x_goals_with_earned_rebounds_score_flurry_adjusted = Column(Numeric(8, 2), nullable=True)
    
    on_ice_a_x_on_goal = Column(Numeric(8, 2), nullable=True)
    on_ice_a_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_flurry_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_score_venue_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_flurry_score_venue_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_shots_on_goal = Column(Integer, nullable=True)
    on_ice_a_missed_shots = Column(Integer, nullable=True)
    on_ice_a_blocked_shot_attempts = Column(Integer, nullable=True)
    on_ice_a_shot_attempts = Column(Integer, nullable=True)
    on_ice_a_goals = Column(Integer, nullable=True)
    on_ice_a_rebounds = Column(Integer, nullable=True)
    on_ice_a_rebound_goals = Column(Integer, nullable=True)
    on_ice_a_low_danger_shots = Column(Integer, nullable=True)
    on_ice_a_medium_danger_shots = Column(Integer, nullable=True)
    on_ice_a_high_danger_shots = Column(Integer, nullable=True)
    on_ice_a_low_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_medium_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_high_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_low_danger_goals = Column(Integer, nullable=True)
    on_ice_a_medium_danger_goals = Column(Integer, nullable=True)
    on_ice_a_high_danger_goals = Column(Integer, nullable=True)
    on_ice_a_score_adjusted_shot_attempts = Column(Integer, nullable=True)
    on_ice_a_unblocked_shot_attempts = Column(Integer, nullable=True)
    on_ice_a_score_adjusted_unblocked_shot_attempts = Column(Integer, nullable=True)
    on_ice_a_x_goals_from_x_rebounds_of_shots = Column(Numeric(8, 2), nullable=True)
    on_ice_a_x_goals_from_actual_rebounds_of_shots = Column(Numeric(8, 2), nullable=True)
    on_ice_a_rebound_x_goals = Column(Numeric(8, 2), nullable=True)
    on_ice_a_x_goals_with_earned_rebounds = Column(Numeric(8, 2), nullable=True)
    on_ice_a_x_goals_with_earned_rebounds_score_adjusted = Column(Numeric(8, 2), nullable=True)
    on_ice_a_x_goals_with_earned_rebounds_score_flurry_adjusted = Column(Numeric(8, 2), nullable=True)
    
    off_ice_f_x_goals = Column(Numeric(8, 2), nullable=True)
    off_ice_a_x_goals = Column(Numeric(8, 2), nullable=True)
    off_ice_f_shot_attempts = Column(Integer, nullable=True)
    off_ice_a_shot_attempts = Column(Integer, nullable=True)

    x_goals_for_after_shifts = Column(Numeric(8, 2), nullable=True)
    x_goals_against_after_shifts = Column(Numeric(8, 2), nullable=True)
    corsi_for_after_shifts = Column(Integer, nullable=True)
    corsi_against_after_shifts = Column(Integer, nullable=True)
    fenwick_for_after_shifts = Column(Integer, nullable=True)
    fenwick_against_after_shifts = Column(Integer, nullable=True)

class AdvancedGoalieStats(Base):
    """Advanced goalie statistics model matching advanced_goalie_stats table schema"""
    __tablename__ = "advanced_goalie_stats"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(Integer, ForeignKey("player_info.id", ondelete="CASCADE"), nullable=False)
    contract_id = Column(Integer, ForeignKey("contracts.id", ondelete="CASCADE"), nullable=False)
    season = Column(Integer, nullable=False)
    playoff = Column(Boolean, nullable=False, default=False)
    team = Column(String(50), nullable=False)
    situation = Column(String(20), nullable=False)
    
    icetime = Column(Numeric(10, 2), nullable=True)
    
    x_goals = Column(Numeric(8, 2), nullable=True)
    goals = Column(Numeric(8, 2), nullable=True)
    
    unblocked_shot_attempts = Column(Integer, nullable=True)
    blocked_shot_attempts = Column(Integer, nullable=True)
    
    x_rebounds = Column(Numeric(8, 2), nullable=True)
    rebounds = Column(Integer, nullable=True)
    
    x_freeze = Column(Numeric(8, 2), nullable=True)
    act_freeze = Column(Integer, nullable=True)

    x_on_goal = Column(Numeric(8, 2), nullable=True)
    on_goal = Column(Integer, nullable=True)
    
    x_play_stopped = Column(Numeric(8, 2), nullable=True)
    play_stopped = Column(Integer, nullable=True)
    
    x_play_continued_in_zone = Column(Numeric(8, 2), nullable=True)
    play_continued_in_zone = Column(Integer, nullable=True)
    x_play_continued_outside_zone = Column(Numeric(8, 2), nullable=True)
    play_continued_outside_zone = Column(Integer, nullable=True)
    flurry_adjusted_x_goals = Column(Numeric(8, 2), nullable=True)
    low_danger_shots = Column(Integer, nullable=True)
    medium_danger_shots = Column(Integer, nullable=True)
    high_danger_shots = Column(Integer, nullable=True)
    low_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    medium_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    high_danger_x_goals = Column(Numeric(8, 2), nullable=True)
    low_danger_goals = Column(Integer, nullable=True)
    medium_danger_goals = Column(Integer, nullable=True)
    high_danger_goals = Column(Integer, nullable=True)

class Player(Base):
    """Player model matching player_info table schema"""
    __tablename__ = "player_info"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    firstname = Column(String(50), nullable=False)
    lastname = Column(String(50), nullable=False)
    team = Column(String(50), nullable=False)
    position = Column(String(50), nullable=False)
    age = Column(Integer, nullable=False)


class Contract(Base):
    """Contract model matching contracts table schema"""
    __tablename__ = "contracts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(Integer, ForeignKey("player_info.id", ondelete="CASCADE"), nullable=False)
    team = Column(String(50), nullable=False)
    start_year = Column(Integer, nullable=False)
    end_year = Column(Integer, nullable=False)
    duration = Column(Integer, nullable=False)
    cap_hit = Column(Numeric(12, 2), nullable=False)
    rfa = Column(Boolean, nullable=False)
    elc = Column(Boolean, nullable=False)
    cap_pct = Column(Numeric(5, 4), nullable=False)
    total_value = Column(Numeric(15, 2), nullable=True)




class BasicPlayerStats(Base):
    """Basic player statistics model matching basic_player_stats table schema"""
    __tablename__ = "basic_player_stats"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(Integer, ForeignKey("player_info.id", ondelete="CASCADE"), nullable=False)
    contract_id = Column(Integer, ForeignKey("contracts.id", ondelete="CASCADE"), nullable=False)
    season = Column(Integer, nullable=False)  
    playoff = Column(Boolean, nullable=False)
    team = Column(String(50), nullable=False)
    gp = Column(Integer, nullable=False)  
    goals = Column(Integer, nullable=False)
    assists = Column(Integer, nullable=False)
    points = Column(Integer, nullable=False)
    plus_minus = Column(Integer, nullable=False)
    pim = Column(Integer, nullable=False)
    shots = Column(Integer, nullable=False)
    shootpct = Column(Numeric(5, 2), nullable=False)

class BasicGoalieStats(Base):
    """Basic goalie statistics model matching basic_goalie_stats table schema"""
    __tablename__ = "basic_goalie_stats"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    player_id = Column(Integer, ForeignKey("player_info.id", ondelete="CASCADE"), nullable=False)
    contract_id = Column(Integer, ForeignKey("contracts.id", ondelete="CASCADE"), nullable=False)
    season = Column(Integer, nullable=False)
    playoff = Column(Boolean, nullable=False)
    team = Column(String(50), nullable=False)
    gp = Column(Integer, nullable=False)
    wins = Column(Integer, nullable=False)
    losses = Column(Integer, nullable=False)
    ot_losses = Column(Integer, nullable=False)
    shots_against = Column(Integer, nullable=False)
    saves = Column(Integer, nullable=False)
    save_percentage = Column(Numeric(5, 2), nullable=False)
    goals_against = Column(Integer, nullable=False)
    goals_against_average = Column(Numeric(5, 2), nullable=False)
    shutouts = Column(Integer, nullable=False)
    time_on_ice = Column(Integer, nullable=False)

